#!/usr/bin/env python3
"""Generate src/mtrtk/rover/drivers/sbg/ids.py from SBG Systems' sbgECom `src/sbgEComIds.h`.

    uv run python scripts/gen-sbg-ids.py [--tag 5.8.935-stable] [--header PATH]

Downloads the header for *tag* from GitHub (or reads a local copy with --header), parses the
`SBG_ECOM_CLASS_*`, `SBG_ECOM_LOG_*` (the `SbgEComLog` enum only: the other log enums reuse the
prefix with overlapping values) and `SBG_ECOM_CMD_*` members, and writes the Python module. The
generated file is committed; re-run this only to bump the tag.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import urllib.request
from pathlib import Path

URL = "https://raw.githubusercontent.com/SBG-Systems/sbgECom/{tag}/src/sbgEComIds.h"
OUT = Path(__file__).resolve().parent.parent / "src/mtrtk/rover/drivers/sbg/ids.py"
MEMBER = re.compile(r"^\s*(SBG_ECOM_(CLASS|LOG|CMD)_[A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)", re.M)
ENTRY = re.compile(r"^\s*(SBG_ECOM_\w+)", re.M)  # every enum member line, valued or not
COMMENT = re.compile(r"/\*.*?\*/|//[^\n]*", re.S)
SENTINEL = re.compile(r"_NUM_(MESSAGES|CMDS)$")  # the trailing count helper, implicitly valued
# Short aliases the driver uses; the header spells the command class LOG_CMD_0.
CLASS_ALIASES = {"CMD_0": "LOG_CMD_0"}


def enum_block(text: str, name: str) -> str:
    start = text.index(f"typedef enum _{name}")
    return text[start : text.index(f"}} {name};", start)]


def members(block: str, kind: str) -> dict[str, int]:
    """`NAME = value` members of one enum block. Raises ValueError when any member line (comments
    stripped, count sentinel aside) is not such a line of *kind*: an implicit value or a stray
    prefix would otherwise yield silently wrong ids."""
    text = COMMENT.sub("", block)
    prefix = f"SBG_ECOM_{kind}_"
    out = {}
    for full, k, value in MEMBER.findall(text):
        if k == kind:
            out[full.removeprefix(prefix)] = int(value, 0)
    entries = [n for n in ENTRY.findall(text) if not SENTINEL.search(n)]
    unparsed = [n for n in entries if n.removeprefix(prefix) not in out or not n.startswith(prefix)]
    if unparsed or len(entries) != len(out):
        raise ValueError(f"{kind}: {len(entries)} members, {len(out)} parsed; check {unparsed}")
    return out


def render(
    tag: str, sha: str, cls: dict[str, int], log: dict[str, int], cmd: dict[str, int]
) -> str:
    def block(name: str, d: dict[str, int], fmt: str) -> list[str]:
        rows = [f'    "{k}": {fmt.format(v)},' for k, v in sorted(d.items(), key=lambda kv: kv[1])]
        return [f"{name}: dict[str, int] = {{", *rows, "}", ""]

    lines = [
        '"""sbgECom message classes and ids. GENERATED by scripts/gen-sbg-ids.py: do not edit.',
        "",
        f"Source: SBG-Systems/sbgECom tag {tag}, src/sbgEComIds.h (MIT licence)",
        f"SHA-256 of the header: {sha}",
        '"""',
        "",
        *block("CLASS", cls, "0x{:02X}"),
        *block("LOG", log, "{}"),
        *block("CMD", cmd, "{}"),
        "LOG_NAME: dict[int, str] = {v: k for k, v in LOG.items()}",
        "CMD_NAME: dict[int, str] = {v: k for k, v in CMD.items()}",
        "",
    ]
    return "\n".join(lines)


def generate(raw: bytes, tag: str) -> str:
    text = raw.decode("utf-8-sig")
    cls = members(enum_block(text, "SbgEComClass"), "CLASS")
    cls.update({alias: cls[real] for alias, real in CLASS_ALIASES.items()})
    log = members(enum_block(text, "SbgEComLog"), "LOG")
    cmd = members(enum_block(text, "SbgEComCmd"), "CMD")
    return render(tag, hashlib.sha256(raw).hexdigest(), cls, log, cmd)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tag", default="5.8.935-stable")
    ap.add_argument("--header", type=Path, help="parse this local copy instead of downloading")
    args = ap.parse_args()
    if args.header:
        raw = args.header.read_bytes()
    else:
        with urllib.request.urlopen(URL.format(tag=args.tag), timeout=30) as resp:
            raw = resp.read()
    out = generate(raw, args.tag)
    OUT.write_text(out)
    print(f"wrote {OUT} ({out.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
